wandb_version: 1

device:
  desc: null
  value: '0'
path:
  desc: null
  value: ./data/datasets/
dataset:
  desc: null
  value: Citeseer
seed:
  desc: null
  value: 42
fix_seed:
  desc: null
  value: true
n_repeated:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.01
weight_decay:
  desc: null
  value: 0
dropout:
  desc: null
  value: 0.3
ratio:
  desc: null
  value: 0.01
num_epoch:
  desc: null
  value: 20
Lambda:
  desc: null
  value: 0.5
alpha:
  desc: null
  value: 1.0e-07
dim1:
  desc: null
  value: 8
dim2:
  desc: null
  value: 32
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709278595.798324
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      - 24
      4: 3.9.18
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
